services:
  postgres:
    image: postgres
    container_name: postgressql
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: senha123
    ports:
      - "5433:5433"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8080